# xp-framework/rdbms

language: php

sudo: false

services:
  - mysql
  - postgresql

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - mysql -e 'create database IF NOT EXISTS test;' -uroot
  - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v6.4.0/setup' -O - | php
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - echo "use=vendor/xp-framework/core" > xp.ini
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - export SQLITE_DSN=sqlite://./test
  - export PGSQL_DSN=pgsql://127.0.0.1/travis_ci_test
  - ./unittest src/test/php
  - export MYSQL_DSN=mysql+x://root@127.0.0.1/test
  - ./unittest src/test/php rdbms.unittest.integration.MySQLIntegrationTest rdbms.unittest.integration.MySQLDeadlockTest
  - export MYSQL_DSN=mysql+i://root@127.0.0.1/test
  - ./unittest src/test/php rdbms.unittest.integration.MySQLIntegrationTest rdbms.unittest.integration.MySQLDeadlockTest
