# xp-framework/rdbms

language: php

sudo: false

services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v6.3.0/setup' -O - | php
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - echo "use=vendor/xp-framework/core" > xp.ini
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - export MYSQL_DSN=mysql+x://root@127.0.0.1/test
  - ./unittest src/test/php