build: false  
shallow_clone: true  

cache:
  - .\xp -> appveyor.yml 
  - vendor -> composer.json

init:
  - set PATH=%PATH%;.\xp
  - set COMPOSER_NO_INTERACTION=1
  - set CACHED=0

install:
  - if exist .\xp (set CACHED=1) else (mkdir .\xp)
  - if %CACHED%==0 cd .\xp
  - if %CACHED%==0 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.2-nts-Win32-VC14-x86.zip -FileName php.zip
  - if %CACHED%==0 appveyor DownloadFile https://getcomposer.org/composer.phar
  - if %CACHED%==0 appveyor DownloadFile https://bintray.com/artifact/download/xp-runners/windows/xp-runners_7.3.3.zip -FileName xp.zip
  - if %CACHED%==0 7z x php.zip -y
  - if %CACHED%==0 7z x xp.zip -y
  - if %CACHED%==0 cd ..

test_script:
  - php -d extension_dir=.\xp\ext -d extension=php_openssl.dll .\xp\composer.phar install --prefer-dist
  - echo vendor/autoload.php > composer.pth
  - xp test src/test/php