build: false  
shallow_clone: true  

cache:
  - .\xp -> appveyor.yml 

init:
  - set PATH=%PATH%;.\xp
  - set COMPOSER_NO_INTERACTION=1

install:
  - mkdir .\xp
  - cd .\xp
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.2-nts-Win32-VC14-x86.zip -FileName php.zip
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - appveyor DownloadFile https://bintray.com/artifact/download/xp-runners/windows/xp-runners_7.3.3.zip -FileName xp.zip
  - 7z x php.zip -y
  - 7z x xp.zip -y

test_script:
  - dir /s
  - php .\xp\composer.phar install --prefer-dist
  - echo vendor/autoload.php > composer.pth
  - xp test src/test/php